/* ********************************************************************************
 * Constants.java
 * 
 * Copyright © 2013 - 2016 VMware, Inc. All Rights Reserved.

 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at http://www.apache.org/licenses/LICENSE-2.0

 * Unless required by applicable law or agreed to in writing, software distributed
 * under the License is distributed on an "AS IS" BASIS, without warranties or
 * conditions of any kind, EITHER EXPRESS OR IMPLIED. See the License for the
 * specific language governing permissions and limitations under the License.
 *
 * *******************************************************************************/
package com.vmware.vrack.hms.common.util;

public class Constants
{

    @Deprecated
    public static final String HMS_APP_TYPE = "HMS";

    // Yags-2014-11-17
    // public static final String REG_EVENT_URI = "/api/1.0/hms/events/subscribe";

    public static final String HMS_DEFAULT_CONFIG_FILE = "config/hms-config.properties";

    public static final Integer UDP_PORT = 0;

    public static final Integer THREAD_POOL_SIZE = 8;

    public static final Integer MONITORING_THREAD_POOL_SIZE = 20;

    // Monitor Frequency in milliseconds
    public static final Integer HOST_NODE_MONITOR_FREQUENCY = 600000;

    public static final String HMS_REGISTER_NME_URI = "/api/1.0/hms/events/register";

    public static final String HMS_ON_DEMAND_EVENTS_FETCH_URI = "/api/1.0/hms/event/host";

    public static final String HMS_ON_DEMAND_SWITCH_EVENTS_FETCH_URI = "/api/1.0/hms/event/switches";

    public static final String HMS_LOCAL_MONITORED_EVENTS_URI = "/api/1.0/hms/events/monitoredevents";

    public static final String NIC_LINK_DOWN_SENSOR_DISCRETE_VALUE = "NIC Link Down";

    public static final String HMS_OOB_ABOUT_ENDPOINT = "/api/1.0/hms/about";

    public static final String HMS_OOB_HEALTH_MONITOR_ENDPOINT = "/api/1.0/hms/event/host/HMS";

    public static final String HOSTS = "hosts";

    public static final String SWITCHES = "switches";

    public static final String HMS_OOB_CPU_INFO_ENDPOINT = "/api/1.0/hms/host/{host_id}/cpuinfo";

    public static final String HMS_OOB_MEMORY_INFO_ENDPOINT = "/api/1.0/hms/host/{host_id}/memoryinfo";

    public static final String HMS_OOB_NIC_INFO_ENDPOINT = "/api/1.0/hms/host/{host_id}/nicinfo";

    public static final String HMS_OOB_HDD_INFO_ENDPOINT = "/api/1.0/hms/host/{host_id}/storageinfo";

    public static final String HMS_OOB_STORAGE_CONTROLLER_INFO_ENDPOINT =
        "/api/1.0/hms/host/{host_id}/storagecontrollerinfo";

    public static final String HMS_OOB_SUPPORTED_OPEARIONS_ENDPOINT = "/api/1.0/hms/service/operations";

    public static final String HMS_OOB_HOST_INFO_ENDPOINT = "/api/1.0/hms/host/{host_id}";

    public static final String HMS_OOB_SWITCH_INFO_ENDPOINT = "/api/1.0/hms/switches/{switch_id}";

    public static final String HMS_OOB_HOST_POWER_STATUS_ENDPOINT = "/api/1.0/hms/host/{host_id}/powerstatus";

    public static final String HMS_OOB_LOG_ENDPOINTS = "/api/1.0/hms/hmslogs";

    /**
     * Event Generator ID of HMS That will be used for the events Generated By HMS
     */
    public static final String HMS_EVENT_GENERATOR_ID = "HMS";

    public static final String HMS_INBAND_THREADLOCAL_EVENT_KEY = "Events";

    public static final String GRANT_EXECUTE_RIGHTS = "chmod +x %s";

    public static final String RESOURCE_BUSY = "Resource is Busy";

    public static final String HMS_OOB_UPGRADE_ENDPOINT = "/api/1.0/hms/upgrade";

    public static final String HMS_OOB_UPGRADE_MONITOR_ENDPOINT = "/api/1.0/hms/upgrade/monitor";

    public static final String HMS_OOB_UPLOAD_ENDPOINT = "/api/1.0/hms/upgrade/upload";

    public static final String PRM_HMS_SERVICESTATE_ENDPOINT = "/vrm-ui/api/1.0/prm/hmsservicestate";

    public static final String HMS_OOB_LOGS_ENDPOINT = "/api/1.0/hms/hmslogs";

    public static final String HMS_OOB_ROLLABACK_ENDPOINT = "/api/1.0/hms/upgrade/rollback";

    public static final String HMS_OOBAGENT_STATUS = "HMS_OOBAGENT_STATUS";

    // FIXME: For RTP1, Management Switch ID is "S0".
    public static final String HMS_MANAGEMENT_SWITCH_ID = "S0";

    // HMS OOB upgrade scripts
    public static final String[] HMS_UPGRADE_OOB_SCRIPTS =
        { "hms_oob_backup.sh", "hms_oob_master_upgrader.sh", "hms_oob_recover.sh", "hms_oob_recover_wrapper.sh",
            "hms_oob_service.sh", "hms_oob_upgrade.sh", "hms_oob_upgrade_wrapper.sh", "hms_oob_validate.sh" };

    /** The Constant BUILD_VERSION. */
    public static final String BUILD_VERSION = "Build-Version";

    /** The Constant PRM_PHYSICALRACKINFO_ENDPOINT. */
    public static final String PRM_PHYSICALRACKINFO_ENDPOINT = "/vrm-ui/api/1.0/prm-service/rack/rackid";

    public static final String CURRENT_ACTIVE_NODE_OPERATION_COUNT_KEY = "CURRENT_ACTIVE_NODE_OPERATION_COUNT_KEY";

    public static final String HTTP = "http";

    public static final String HTTPS = "https";

    public static final String HMS_OOB_CREATE_KEYS = "/api/1.0/hms/certificate/create";

    public static final String HMS_OOB_UPLOAD_CERTIFICATE = "/api/1.0/hms/certificate/upload";

    public static final String HMS_OOB_HANDSHAKE = "/api/1.0/hms/handshake";

    public static final String HMS_OOB_INVENTORY_RELOAD = "/api/1.0/hms/inventory/reload";

    public static final String HMS_OOB_INVENTORY_REFRESH = "/oobagent/inventory/refresh";

    public static final String HMS_OOB_INVENTORY_IS_LOADED = "/api/1.0/hms/inventory/isloaded";

    public static final String HMS_MGMT_SWITCH_CREATE_SSH_KEYS = "/api/1.0/hms/sshkeys/create";

    public static final String HMS_MGMT_SWITCH_DHCP_LEASE_FILE_KEY = "hms.mgmt.switch.dhcp.lease.file";

    public static final String HMS_OOB_NEW_HOSTS = "/api/1.0/hms/newhosts";

    public static final String HMS_OOB_REFRESHINVENTORY_API = "/api/1.0/hms/refreshinventory";

    public static final String HMS_AGGREGATOR_IP_DELIMITER = "\\|";

    public static final String VRM = "VRM";

    public static final String AGGREGATOR = "AGGREGATOR";

    public static final String FILE_SEPERATOR = "/";

    public static final String HMS_UPGRADE_DIR = "hms.upgrade.dir";

    /** The Constant HMS_HOST_REACHABILITY_VERIFICATION_COMMAND_TEMPLATE. */
    public static final String HMS_HOST_REACHABILITY_VERIFICATION_COMMAND_TEMPLATE =
        "ping -c 1 -W 30 %s > /dev/null 2>&1";

    public static final String HMS_INV_FROM_AGG_AVAILABILITY_STATUS = "hms.inv.from.agg.availability.status";

}
